# Generated by Django 4.2.7 on 2026-09-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], max_length=20, verbose_name='递交前状态')),
                ('to_status', models.CharField(choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], default='submitted', max_length=20, verbose_name='递交后状态')),
                ('ps_title', models.CharField(blank=True, max_length=200, verbose_name='个人陈述标题')),
                ('ps_version_number', models.IntegerField(blank=True, null=True, verbose_name='个人陈述版本号')),
                ('ps_content', models.TextField(blank=True, verbose_name='个人陈述正文快照')),
                ('ps_word_count', models.IntegerField(default=0, verbose_name='个人陈述字数')),
                ('application_round_name', models.CharField(blank=True, max_length=50, verbose_name='申请批次名称')),
                ('application_round_deadline', models.DateField(blank=True, null=True, verbose_name='申请批次截止日期')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='递交时间')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='回退时间')),
                ('rollback_reason', models.TextField(blank=True, verbose_name='回退原因')),
                ('restored_status', models.CharField(blank=True, choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], max_length=20, verbose_name='回退后恢复状态')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_snapshots', to='applications.applicationproject', verbose_name='申请项目')),
            ],
            options={
                'verbose_name': '递交快照',
                'verbose_name_plural': '递交快照',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionSnapshotMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('material_type', models.CharField(blank=True, max_length=20, verbose_name='材料类型')),
                ('material_type_display', models.CharField(blank=True, max_length=50, verbose_name='材料类型显示')),
                ('description', models.TextField(blank=True, verbose_name='材料说明')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必需')),
                ('is_completed', models.BooleanField(default=False, verbose_name='递交时是否已完成')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='递交时文件名')),
                ('file_url', models.CharField(blank=True, max_length=500, verbose_name='递交时文件地址')),
                ('uploaded_by_name', models.CharField(blank=True, max_length=150, verbose_name='上传人')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_entries', to='materials.materialitem', verbose_name='来源材料')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='submissions.submissionsnapshot', verbose_name='所属递交快照')),
            ],
            options={
                'verbose_name': '递交快照材料',
                'verbose_name_plural': '递交快照材料',
                'ordering': ['snapshot', '-is_required', 'material_type', 'name'],
            },
        ),
    ]
