# Generated by Django 4.2.7 on 2026-09-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        ('submissions', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsnapshot',
            name='application_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_snapshots', to='universities.applicationdeadline', verbose_name='申请批次'),
        ),
        migrations.AddField(
            model_name='submissionsnapshot',
            name='ps_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_snapshots', to='documents.document', verbose_name='个人陈述文书'),
        ),
        migrations.AddField(
            model_name='submissionsnapshot',
            name='ps_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_snapshots', to='documents.documentversion', verbose_name='个人陈述版本'),
        ),
    ]
