# Generated by Django 4.2.7 on 2026-09-20 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsnapshot',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_submission_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='回退操作人'),
        ),
        migrations.AddField(
            model_name='submissionsnapshot',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='递交人'),
        ),
        migrations.AddConstraint(
            model_name='submissionsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('rolled_back_at__isnull', True)), fields=('application',), name='unique_active_snapshot_per_application'),
        ),
    ]
