# Generated by Django 4.2.7 on 2026-09-20 03:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], default='planning', max_length=20, verbose_name='申请状态')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='申请费')),
                ('fee_paid', models.BooleanField(default=False, verbose_name='申请费已缴纳')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('result_date', models.DateTimeField(blank=True, null=True, verbose_name='结果公布时间')),
                ('submission_locked', models.BooleanField(default=False, verbose_name='递交锁定')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '申请项目',
                'verbose_name_plural': '申请项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], max_length=20, null=True, verbose_name='原状态')),
                ('to_status', models.CharField(choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], max_length=20, verbose_name='新状态')),
                ('change_reason', models.TextField(blank=True, verbose_name='变更原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '状态变更记录',
                'verbose_name_plural': '状态变更记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_no', models.PositiveIntegerField(verbose_name='快照序号')),
                ('status', models.CharField(choices=[('active', '生效中'), ('rolled_back', '已回退')], default='active', max_length=20, verbose_name='快照状态')),
                ('previous_status', models.CharField(choices=[('planning', '规划中'), ('preparing', '准备材料'), ('submitted', '已提交'), ('waiting', '等待结果'), ('admitted', '已录取'), ('rejected', '已拒'), ('waitlisted', '候补'), ('deferred', '延期')], default='preparing', max_length=20, verbose_name='递交前状态')),
                ('application_round_name', models.CharField(blank=True, max_length=100, verbose_name='申请批次名称')),
                ('application_round_deadline', models.DateField(blank=True, null=True, verbose_name='批次截止日期')),
                ('ps_document_title', models.CharField(blank=True, max_length=200, verbose_name='文书标题')),
                ('ps_version_number', models.IntegerField(blank=True, null=True, verbose_name='版本号')),
                ('ps_content', models.TextField(blank=True, verbose_name='版本正文快照')),
                ('ps_word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('ps_change_note', models.TextField(blank=True, verbose_name='版本修改说明')),
                ('materials_snapshot', models.JSONField(default=list, verbose_name='材料快照')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='递交时间')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True, verbose_name='回退时间')),
                ('rollback_reason', models.TextField(blank=True, verbose_name='回退原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_snapshots', to='applications.applicationproject', verbose_name='申请项目')),
            ],
            options={
                'verbose_name': '递交快照',
                'verbose_name_plural': '递交快照',
                'ordering': ['-snapshot_no'],
            },
        ),
    ]
