# Generated by Django 4.2.7 on 2026-09-20 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
        ('applications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionsnapshot',
            name='rolled_back_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolled_back_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='回退操作人'),
        ),
        migrations.AddField(
            model_name='submissionsnapshot',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='递交人'),
        ),
        migrations.AddField(
            model_name='statuschangehistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.applicationproject', verbose_name='申请项目'),
        ),
        migrations.AddField(
            model_name='statuschangehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='applicationproject',
            name='application_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.applicationdeadline', verbose_name='申请轮次'),
        ),
        migrations.AddField(
            model_name='applicationproject',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='applications.submissionsnapshot', verbose_name='当前递交快照'),
        ),
        migrations.AddField(
            model_name='applicationproject',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.program', verbose_name='申请专业'),
        ),
        migrations.AddField(
            model_name='applicationproject',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AddField(
            model_name='applicationproject',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='目标院校'),
        ),
        migrations.AddConstraint(
            model_name='submissionsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('application',), name='unique_active_snapshot_per_application'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionsnapshot',
            unique_together={('application', 'snapshot_no')},
        ),
    ]
